name: Fast Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fast-ci:
    name: Quick CI Checks & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Quality Gate Pipeline
        run: make quality-gate
